### ISSUE TITLE
禁用 Pandoc 的 Highlight

### ISSUE THREAD

**Issue by argvchs** [LynxCatTheThird/web-v2#2]
```yaml
# _config.yml
pandoc:
  extra:
    - "no-highlight": # here
  extensions:
    - "+hard_line_breaks"
    - "+emoji"
    - "-implicit_figures"
```

这样 Pandoc 和 Hexo-Renderer-Marked 的渲染就一样了，没有 `class="sourceCode"` 了

还有 `functions.js` 也可以简化
